version: '3'

services:
  postgres:
    image: postgres:13.1
    container_name: ktor_recipe_postgress
    ports:
      - 5434:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: recipe
      POSTGRES_PASSWORD: recipe
      POSTGRES_DB: recipe
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
      TZ: 'Asia/Tokyo'
    restart: always